services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: tkt
      MYSQL_USER: tkt
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_PASSWORD: N1mpTkt=)
      MYSQL_ROOT_PASSWORD: N1mpTkt=)
    healthcheck:
      test: ['CMD', 'mysqladmin' ,'ping', '-h', 'localhost']
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 20
    volumes:
      - tkt_data:/var/lib/mysql:rw
    networks:
      - tkt

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_PORT: 3306
      PMA_HOST: mysql
      PMA_USER: tkt
      PMA_PASSWORD: N1mpTkt=)
    ports:
      - 8080:80
    networks:
      - tkt

volumes:
  tkt_data:
    name: tkt_data
  mailpit_data:
    name: mailpit_data

networks:
  tkt:
    name: tkt
    driver: bridge